version: '3.8'

services:
  app:
    container_name: anime-guesser-bot
    image: anime-guesser-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    restart: unless-stopped
